#!/usr/bin/env ruby

commands = "
cd ~/current
rm -rf public/javascripts/jsus/*
rm -rf public/stylesheets
RAILS_ENV=production rake lsd:relink_packages sass:update sitemap:refresh:no_ping
".strip.split("\n").join(" && ")

`dotcloud run microdata.www -- "#{commands}"`

#  db:migrate posts:reload