#!/usr/bin/env ruby

`dotcloud push mdtools`

commands = "
cd ~/current/lib/linker
ruby ./extconf.rb
make
cd ~/current
rm -rf public/javascripts/jsus/*
rm -rf public/stylesheets
RAILS_ENV=production rake lsd:relink_packages sass:update sitemap:refresh
".strip.split("\n").join(" && ")

`dotcloud run mdtools.www -- "#{commands}"`

# examples:reload db:migrate posts:reload sitemap:refresh:no_ping